# Generated by Django 4.2.7 on 2023-11-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_manager', '0002_remove_contact_organization'),
        ('profile_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', to='contacts_manager.contact'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
